config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end
  # Defines the root path route ("/")
  # get "blog_post/new", to:"blog_post#new", as: :new_post
  # get "blog_post/:id", to: "blog_post#show", as: :blog_post
  # post "blog_post", to:"blog_post#create", as: :blog_posts
  # get "blog_post/:id/edit", to: "blog_post#edit", as: :edit_post
  # patch "blog_post/:id", to: "blog_post#update"
  # delete "blog_post/:id", to: "blog_post#destroy"
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
has_rich_text :content
  scope :sorted, ->  {order(Arel.sql("published_at ASC NULLS FIRST")).order(updated_at: :desc)}
  validates :title, presence: true
  validates :content, presence: true
  scope :draft, -> {where published_at: nil}
  scope :published, -> {where "published_at <= ?", Time.current}
  scope :scheduled, -> {where "published_at > ?", Time.current}



  def draft?
    published_at.nil?
  end
  def published?
    published_at? && published_at <= Time.current
  end
  def scheduled?
    published_at? && published_at > Time.current?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
include ActionView::RecordIdentifier
  before_action :authenticate_user!

  def destroy
    @blog_post=BlogPost.find(params[:blog_post_id])
    @blog_post.cover_image.purge_later
    respond_to do |format|
    format.html {redirect_to edit_blog_post_path(@blog_post)}
    format.turbo_stream {render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image))}
    end
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :blog_line, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @blog_post= user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    @pagy, @blog_post = pagy(@blog_post)
  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
  end

  def show
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @blog_post=BlogPost.new
  end

  def create
    @blog_post=BlogPost.new(set_blog)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(set_blog)
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
     @blog_post.destroy
      redirect_to root_path
  end

  private
  def set_blog
    params.require(:blog_post).permit(:title,:content,:cover_image,:published_at)
  end

  def blog_line
    if user_signed_in?
      @blog_post=  BlogPost.find(params[:id])
    else
      @blog_post= BlogPost.published.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/blog_post_helper.rb
module BlogPostHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post) do |form| %>
<div>
<h2><%= form.label :Title %>:</h2>
<%= form.text_field :title %>
</div>

<div>
<h2><%= form.label :content %>:</h2>
<%= form.rich_text_area :content %>
</div>


<div>
<h2><%= form.label :cover_image %>:</h2>
<% if @blog_post.cover_image.present? %>

<%#= form.label :published_at%>
<%#= form.datetime_select :published_at, include_blank: true %>
<div>
<div>
    <p style="width:200px" <%= dom_id(@blog_post, :cover_image) %>>
    <%= image_tag @blog_post.cover_image %></p>
    <%= link_to "remove cover", blog_post_cover_image_path(@blog_post), data:{turbo_method: :delete, turbo_confirm:"are you sure do you want to delte cover image?"}, class:"btns" %>
    </div>
<% end %>
<br>
<%= form.file_field :cover_image %>
</div>
</div>
<br>
<%= form.submit  class:"btns"%>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Post Page</h1>
<%= render partial: "form" %>
<br>

<%= button_to "delete", @blog_post, method: :delete, data: {turbo_confirm:"are you sure?"}, class:"btns" %>
<br>
<%= link_to "Home Page", blog_posts_path, class:"btns"%>

app/views/blog_posts/index.html.erb
<h1>This is Blog Post site for Practice</h1>
<% @blog_post.each do |blog_post| %>
<div>
<% if blog_post.draft? %>
<h3 style=" background-color:rgb(207, 197, 196)">Draft</h3>
<% elsif blog_post.published? %>
<h3 style=" background-color:rgb(186, 235, 108)">Published</h3>
<% else %>
<h3 style=" background-color:rgb(235, 214, 108)">Scheduled</h3>
<% end %>
</div>

<h2><%= link_to blog_post.title, blog_post %></h2>
<% end %>
<div>
    <% if @pagy.count > @pagy.items %>
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    <% end %>
</div>

app/views/blog_posts/new.html.erb
<h1>Create Blog</h1>
<%= render partial: "form" %>

app/views/blog_posts/show.html.erb
<h2>Title:</h2><p> <%= @blog_post.title %></p>
<h2>Content:</h2><p> <%= @blog_post.content %></p>
<% if @blog_post.cover_image.present? %>
<h2>Cover image:</h2><p> <%= image_tag @blog_post.cover_image %></p>
<% end %>
<%= link_to "edit", edit_blog_post_path(@blog_post), class:"btns" %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext",  "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<body class="prose body">
<center>
     <p class="notice" ><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <div>
        <% if user_signed_in? %>
        <%= link_to "New Post", new_blog_post_path, class: "btns" %>
        <br><br>
        <%= button_to "Log out", destroy_user_session_path, class:"btns", method: :delete%>
        <% else %>
        <div><%= link_to "Login", new_user_session_path, class:"btns" %></div>

        <% end %>
    <%= yield %>
    </center>
</body>
</html>